name: Weekly ETL Data Update

on:
  schedule:
    - cron: '30 20 * * 0'   # Every Sunday at 02:00 AM IST (20:30 UTC Saturday)
  workflow_dispatch:         # Allows manual triggering from GitHub UI

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup environment variables
        env:
          CRUNCHBASE_API_KEY: ${{ secrets.CRUNCHBASE_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: |
          echo "Loaded API keys from GitHub secrets."
          echo "CRUNCHBASE_API_KEY=${CRUNCHBASE_API_KEY}" >> $GITHUB_ENV
          echo "NEWS_API_KEY=${NEWS_API_KEY}" >> $GITHUB_ENV

      - name: Run ETL pipeline
        run: |
          echo "Starting ETL pipeline..."
          python etl/fetch_kaggle.py || echo "No Kaggle update"
          python etl/clean_transform.py
          python etl/load_to_sqlite.py
          echo "ETL pipeline finished successfully."

      - name: Commit database updates
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add db/funding.db data/interim/*.csv || true
          git commit -m "🗓️ Automated ETL run: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit."
          git push || true

      - name: Notify success
        run: echo "✅ ETL pipeline completed successfully!"
